services:
  - type: web
    plan: free
    name: CosmicBotz-Rename-2GB
    env: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/CosmicBotz/Rename-2gb-bot
    branch: master
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: FORCE_SUB
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: BIN_CHANNEL
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_URL
        sync: false
      - key: START_PIC
        sync: false
      - key: ADMIN
        sync: false
      - key: WEBHOOK
        value: "True"
      - key: MEDIA_POOL_SIZE
        value: "6"
      - key: RAM_CACHE_MAX_MB
        value: "40"
      - key: WZGRAM_MAX_READ_AHEAD
        value: "24"
      - key: MALLOC_ARENA_MAX
        value: "2"
